### ISSUE TITLE
给作者提点小优化点，顺便换换友链

### ISSUE THREAD

**Issue by ha0719** [liaocp666/Jasmine#38]
希望作者有时间能优化的，不能优化也没关系，已经很不错了
1、文章缩略图支持提取文章内第一张图片（现在是挂了一个插件实现的）；
2、缩略图可选在文章左侧或者右侧（当然改代码也可以实现）；
3、左侧的图标导航和顶部的文字导航，hover在图标上的时候，文字会盖住右边的文字导航，希望修复；
4、主题颜色，建议可以自定义；
5、说说的样式，建议增加一个点击进行详情页的链接，比如评论；

有空期望看到新版本，手动狗头保命

有换链接的可以到 www.huangao.net 留言，10年老站希望看到你的链接，嘿嘿

**Comment by liaocp666** [comment]
1、2、3、5 不考虑
4：主题选项 - 自定义样式按下面的样式，自己改需要颜色
```css
:root{
            --primary-bg: #a2c6e1;
          --link-color: #668aa5;
          --link-hover-color: #668aa5;
}
```
